models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return bool whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                ->setReplyTo([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\models\db\User;

/**
 * LoginForm is the model behind the login form.
 *
 * @property-read User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $key;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['key'], 'required'],
            [['key'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['key' => 'secret_id']],
        ];
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            $user = User::findIdentityByAccessToken($this->key);
            if ($user) {
                return Yii::$app->user->login($user, 3600*24*30);
            } else {
                return false;
            }
        }
        
        return false;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\db\User;
use app\service\Santa;
use yii\db\Transaction;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'index', 'peer', 'wishlist'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get', 'post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
            $service = new Santa();
            /* @var $user User */
            $user = \Yii::$app->user->identity;
            
            return $this->render('index', [
                'user' => $user,
                'availableTargets' => $service->getAllAvailableTargets($user),
            ]);
//        }
    }
    
    public function actionWishlist()
    {
        /* @var $user User */
        $user = \Yii::$app->user->identity;
        
        $user->setScenario(User::SCENARIO_WISHLIST);
        
        if (\Yii::$app->request->isPost) {
            if ($user->load(\Yii::$app->request->post()) && $user->save()) {
                $this->goHome();
            } else {
                return $this->render('wishlist', ['model' => $user]);
            }
        } else {
            return $this->render('wishlist', ['model' => $user]);
        }
    }


    public function actionPair($key)
    {
        $transaction = \Yii::$app->db->beginTransaction(Transaction::SERIALIZABLE);
        
        try {
            $service = new Santa();
            /* @var $user User */
            $user = \Yii::$app->user->identity;
            
            $target = User::findOne(['public_id' => $key]);

            $service->pair($user, $target);
            
            $transaction->commit();
        } catch (\Exception $e) {
            $transaction->rollBack();
            \Yii::$app->session->setFlash('error', $e->getMessage());
        }
            
        $this->goHome();
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin($key = null)
    {
        $form = new LoginForm();
        
        if (\Yii::$app->request->isPost) {
            $form->load(\Yii::$app->request->post());
        } else if ($key) {
            $form->key = $key;
        }
        
        if ($form->validate() && $form->login()) {
            $this->goHome();
        } else {
            return $this->render('login', ['model' => $form]);
        }
//            $user = User::findIdentityByAccessToken($key);
//            if ($user) {
//                Yii::$app->user->login($user, 365*24*3600);
//                return $this->goHome();
//            } else {
//                $this->render('login');
//            }
//        return $this->render('login', ['model' => $form]);
    }
    

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100" style="background-color: #add8e6">
<?php $this->beginBody() ?>

<header>
</header>

<main role="main h-100" class="flex-shrink-0">
    <div class="container h-100" style="background-color: white">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

$this->title = 'Тайный Санта';
?>
<div class="site-index">
    <div class="navbar alert-dark h3">Привет, <?= $user->name ?>! <a href="<?= \Yii::$app->urlManager->createUrl(['site/logout']) ?>">Выйти</a></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 ">

                <?php if ($user->isSanta()) { ?> 
                <p> Ты <?=$user->isMan() ? 'выбрал' : 'выбрала'?>, кому дарить подарок:</p>
                        <div class="card float-left" style="width: 220px; height: 320px; text-align: center; vertical-align: middle; background-color: lightblue">
                            <h2 style="color: red"><?= $user->getTarget()->one()->name ?></h2>                                
                        </div>
                    <p class="clearfix"></p>
                    <div class="card" id="wishlist">
                        <h4>Вишлист:</h4>
                        <?= nl2br($user->getTarget()->one()->wishlist ?? 'Пока не заполнен'); ?> 
                    </div>
                <?php } else { ?>
                    <p> Выбери, кому дарить подарок!</p>
                <?php } ?>
                <div>
                    <?php foreach ($availableTargets as $target) { ?>
                        <div class="card float-left" style="width: 220px">
                            <a style="margin: 10px" href="<?= \Yii::$app->urlManager->createUrl(['site/pair', 'key' => $target->public_id]) ?>">
                                <img src="img/Somebody.png" alt="?"/>
                            </a>
                        </div>
                    <?php } ?>
                </div>

            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body" style="background-color: lightblue">
                        <h3 class="card-title">Ваш Тайный Санта</h3>
                        <?php if ($user->hasSanta()) { ?> 
                            <p>Поздравляем, у вас уже есть Тайный Санта!</p>
                        <?php } else { ?>
                            <p>У вас еще нет Тайного Санты.</p>
                        <?php } ?>
                    </div>
                </div>
                
                <a class="btn-primary" href="<?= \Yii::$app->urlManager->createUrl(['site/wishlist']) ?>">Твой вишлист</a>

            </div>
        </div>
    </div>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Введите ваш секретный код:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'enableClientScript' => false,
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'key')->textInput(['autofocus' => true]) ?>


        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/wishlist.php
<?php

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Вишлист';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-wishlist">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Твой вишлист:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'wishlist-form',
        'layout' => 'horizontal',
        'enableClientScript' => false,
    ]); ?>

        <?= $form->field($model, 'wishlist')->textarea(['autofocus' => true, 'rows' => 20]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>